#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
#
if [[ -z "$TMPDIR" ]]; then
  export TMPDIR="/tmp/zsh-$UID"
fi

if [[ ! -d "$TMPDIR" ]]; then
  mkdir "$TMPDIR"
  chmod 700 "$TMPDIR"
fi

########################
# Petes customizations #
########################
source ~/bin/utils_sirkkalap.sh

function svndiff {
  svn diff "$@" | colordiff | less -RFX
}

function setPaths()
{
  local new_path
  # Set paths
  if [[ -e ~/.paths.d ]]; then
    for new_path in $(cat ~/.paths.d/*); do
      utils_sirkkalap::prepend_path_if_exists PATH ${new_path}
    done
  fi
}

function setEnv()
{
  local script
  # Set env
  if [[ -e ~/.env.d ]]; then
    for script in $(ls ~/.env.d/*.sh); do
      source ${script}
    done
  fi
}

setPaths
setEnv

# set env
if [ -e ~/.env.d ]; then
    for script in ~/.env.d/*.sh(N); do
    source ${script}
  done
fi

# For machines with local home
if [[ -e ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

# For machines with shared homes, use hostname to select your config
if [[ -e ~/.zshrc.$(hostname) ]]; then
  source ~/.zshrc.$(hostname)
fi

# Autojump (j fofoofoo)
if [[ -s /usr/share/autojump/autojump.zsh ]]; then
  source /usr/share/autojump/autojump.zsh
else
    command -v brew >/dev/null 2>&1 && [[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh
fi

zle -C complete-file complete-word _generic
zstyle ':completion:complete-file::::' completer _files
bindkey '^xF' complete-file

zstyle ':completion:*' completer _complete _ignored _files

alias rm='nocorrect rm'
alias cp='nocorrect cp'
alias mv='nocorrect mv'

# http://tosbourn.com/view-markdown-files-terminal/
function rmd () {
  pandoc $1 | lynx -stdin
}

# Under Ubuntu Terminal text cursor went missing while moving it with cursor
# keys.
# https://github.com/zsh-users/zsh-syntax-highlighting/issues/171#issuecomment-140335051
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[cursor]=underline

#########################
# /Petes customizations #
#########################
